version: "3.8"

services:
  nginx:
    container_name: nginx
    env_file: ../.env
    build:
      context: requirements/nginx
      dockerfile: Dockerfile
    image: nginx:nginx
    deploy:
      restart_policy:
        condition: any
    # volumes:
    #   - wordpress:/mywebside
    networks:
      - "docker-network"
    ports:
      - '430:430'

  wordpress:
    container_name: wordpress
    env_file: ../.env
    build:
      context: requirements/wordpress
      dockerfile: Dockerfile
    image: wordpress:wordpress
    deploy:
      restart_policy:
        condition: any
    # volumes:
    #   - wordpress:/wordpress/var/www/html/
    networks:
      - "docker-network"
    depends_on: 
      - mariadb

  mariadb:
    container_name: mariadb
    env_file:  ../.env
    build:
      context: requirements/mariadb
      dockerfile: Dockerfile
    image: mariadb:mariadb
    deploy:
      restart_policy:
        condition: any
    # volumes:
    # - type: bind
    #   source: "/home/dmonfrin/data/db"
    #   target : "/var/lib/mysql"



    networks:
      - "docker-network"
    depends_on:
      - nginx

networks:
  docker-network:


# volumes:
#   wordpress:
#     type: "bind"
#     source: "/home/dmonfrin/data/wordpress"
#   db:
#     type: "bind"
#     source: 
   
