version: "3.8"

services:
  nginx:
    container_name: nginx
    env_file: .env
    build:
      context: requirements/nginx
      dockerfile: Dockerfile
    image: nginx:nginx
    stdin_open: true
    volumes:
    - "../home/dmonfrin/data/wordpress:/var/www/html/"
    restart: always
    networks:
      - "docker-network"
    ports:
      - '430:430'
    depends_on:
    - wordpress

  wordpress:
    container_name: wordpress
    env_file: .env
    build:
      context: requirements/wordpress
      dockerfile: Dockerfile
    image: wordpress:wordpress
    restart: always
    volumes:
    - "../home/dmonfrin/data/wordpress:/var/www/html/"
    stdin_open: true
    networks:
      - "docker-network"
    depends_on: 
      - mariadb

  mariadb:
    container_name: mariadb
    env_file:  .env
    tty: true
    stdin_open: true
    build:
      context: requirements/mariadb
      dockerfile: Dockerfile
    image: mariadb:mariadb
    restart: always
    volumes:
    - "../home/dmonfrin/data/database:/var/lib/mysql"
    networks:
      - "docker-network"

networks:
  docker-network:
    driver: bridge


# volumes:
#   WordPress:
#     type: "bind"
#     source: "/home/dmonfrin/data/wordpress"
#   DB:
#     type: "bind"
#     source: 


listen = /run/php/php7.4-fpm.sock

sed 's/listen = /run/php/php7.4-fpm.sock/Listen 127.0.0.1:9000/g' 
