version: "3.8"

services:
  nginx:
    container_name: nginx
    env_file: .env
    build:
      context: requirements/nginx
      dockerfile: Dockerfile
    image: nginx:nginx
    volumes:
    - "/home/dmonfrin/data/wordpress:/var/www/html/"
    deploy:
      restart_policy:
        condition: any
    networks:
      - "docker-network"
    ports:
      - '430:430'

  wordpress:
    container_name: wordpress
    env_file: .env
    build:
      context: requirements/wordpress
      dockerfile: Dockerfile
    image: wordpress:wordpress
    deploy:
      restart_policy:
        condition: any
    volumes:
    - "/home/dmonfrin/data/wordpress:/var/www/html/"
    # - type: bind
    #   source: "/home/dmonfrin/data/db"
    #   target : "/var/lib/mysql""
    # volumes:
    #   - wordpress:/wordpress/var/www/html/
    networks:
      - "docker-network"
    depends_on: 
      - mariadb

  mariadb:
    container_name: mariadb
    env_file:  .env
    tty: true
    stdin_open: true
    build:
      context: requirements/mariadb
      dockerfile: Dockerfile
    image: mariadb:mariadb
    deploy:
      restart_policy:
        condition: any
    volumes:
    - "/home/dmonfrin/data/database:/var/lib/mysql"
    networks:
      - "docker-network"
    depends_on:
      - nginx

networks:
  docker-network:
    driver: bridge


# volumes:
#   WordPress:
#     type: "bind"
#     source: "/home/dmonfrin/data/wordpress"
#   DB:
#     type: "bind"
#     source: 
   
