version: "3.8"

services:
  nginx:
    container_name: nginx
    env_file: .env
    build:
      context: requirements/nginx
      dockerfile: Dockerfile
    image: nginx:nginx
    stdin_open: true
    volumes:
    - "wordpress:/var/www/html/"
    restart: always
    networks:
      - "docker-network"
    ports:
      - '443:443'
    depends_on:
    - wordpress

  wordpress:
    container_name: wordpress
    env_file: .env
    build:
      context: requirements/wordpress
      dockerfile: Dockerfile
    image: wordpress:wordpress
    restart: always
    volumes:
    - "wordpress:/var/www/html/"
    stdin_open: true
    networks:
      - "docker-network"
    depends_on: 
      - mariadb

  mariadb:
    container_name: mariadb
    env_file:  .env
    tty: true
    stdin_open: true
    build:
      context: requirements/mariadb
      dockerfile: Dockerfile
    image: mariadb:mariadb
    restart: always
    volumes:
    - "db:/var/lib/mysql"
    networks:
      - "docker-network"

networks:
  docker-network:
    driver: bridge


volumes:
  wordpress:
    driver: local
    name: wordpress
    driver_opts:
      o: bind
      device: /your/folder/path/wordpress/
      type: none
  db:
    driver: local
    name: db
    driver_opts:
      o: bind
      device: /your/folder/path/database/
      type: none
