FROM debian:bullseye

RUN apt update && apt upgrade -y

RUN apt install -y php-cgi php-common php-fpm php-mbstring php-zip php-net-socket php-gd php-mysql php-bcmath

#RUN apt install php -y

RUN apt install wget -y

# RUN apt install xfz -y
COPY ./conf/wp-config.php .

RUN sed 's+listen+listen = wordpress:9000+g' ./etc/php/7.4/fpm/pool.d/www.conf
COPY ./conf/www.conf ./etc/php/7.4/fpm/pool.d/www.conf

COPY ./tools/wordpress.sh .

RUN mkdir -p ./run/php

# RUN mkdir /var/www && mkdir /var/www/html

#RUN bash wordpress.sh

#CMD [ "sistem", "" ]
#CMD [ "bash", "wordpress.sh" ]

 #RUN service php7.4-fpm start
 
 #CMD [ "php7.4-fpm", "-F", "-R" ]

 #CMD [ "service", "php7.4-fpm", "start", "&&", "php7.4-fpm", "-F", "-R" ]